-- Insert dummy sellers
INSERT INTO sellers (
    id,
    name,
    phone,
    address,
    photo_url,
    hire_date,
    salary,
    contract_type,
    birth_date,
    email,
    active,
    created_at,
    updated_at
) VALUES
    (
        uuid_generate_v4(),
        'Luis Ramírez',
        '809-555-1001',
        'Calle 1ra #23, Los Prados, Santo Domingo',
        'https://randomuser.me/api/portraits/men/1.jpg',
        '2023-01-15',
        35000.00,
        'FULL_TIME',
        '1990-05-20',
        'luis.ramirez@company.com',
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        uuid_generate_v4(),
        'Ana Martínez',
        '809-555-1002',
        'Av. Independencia #45, Gazcue, Santo Domingo',
        'https://randomuser.me/api/portraits/women/1.jpg',
        '2023-02-01',
        32000.00,
        'FULL_TIME',
        '1992-08-15',
        'ana.martinez@company.com',
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        uuid_generate_v4(),
        'Pedro Sánchez',
        '809-555-1003',
        'Calle Principal #67, Bella Vista, Santo Domingo',
        'https://randomuser.me/api/portraits/men/2.jpg',
        '2023-03-10',
        28000.00,
        'PART_TIME',
        '1988-12-03',
        'pedro.sanchez@company.com',
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        uuid_generate_v4(),
        'María Pérez',
        '809-555-1004',
        'Av. Abraham Lincoln #89, Piantini, Santo Domingo',
        'https://randomuser.me/api/portraits/women/2.jpg',
        '2023-04-01',
        40000.00,
        'FULL_TIME',
        '1991-03-25',
        'maria.perez@company.com',
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        uuid_generate_v4(),
        'José García',
        '809-555-1005',
        'Calle 27 #34, Naco, Santo Domingo',
        'https://randomuser.me/api/portraits/men/3.jpg',
        '2023-05-15',
        25000.00,
        'CONTRACTOR',
        '1993-07-12',
        'jose.garcia@company.com',
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
ON CONFLICT (email) DO NOTHING;